server:
  prot:8087
  context-path:bolg
  
spring:
  datasource:
    url:"jdbc:mysql://localhost:3306/aboutjpa?useUnicode=true&characterEncoding=UTF-8"
    username:root
    password:root
    driver-class-name:com.mysql.jdbc.Driver
    type:com.mchange.v2.c3p0.ComboPooledDataSource